server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lemon?useSSL=false
    username: root
    password: zhang123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    jpa:
      # 配置 DBMS 类型
      database: MYSQL
      # 配置是否将执行的 SQL 输出到日志
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            # 配置开启自动更新表结构
            auto: update

app-config:
  url: https://api.weixin.qq.com/sns/jscode2session
  appId: wxa70d9fa4930a90c4
  appSecret: 23123ecfc3c3128bcfd3079c401f3da9
  grant_type: authorization_code
